version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: bip
      POSTGRES_PASSWORD: bip
      POSTGRES_DB: bip_cms
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bip -d bip_cms']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
