/** UI label dictionaries for en / ku (Sorani) / ar — used by seed scripts. */

export type LabelDict = Record<string, string>

export const LABELS_EN: LabelDict = {
  register: 'Register',
  learnMore: 'Learn More',
  explore: 'Explore',
  viewAll: 'View All',
  submit: 'Submit',
  join: 'Join',
  sendMessage: 'Send Message',
  contact: 'Contact',
  joinUs: 'Join Us',
  askBipAi: 'Ask BIP AI',
  close: 'Close',
  closeDialog: 'Close dialog',
  closeOverlay: 'Close {title}',
  navHome: 'Home',
  navAbout: 'About',
  navSummits: 'Summits',
  navNews: 'News & Blogs',
  navPrograms: 'Programs',
  navContactUs: 'Contact Us',
  navWorkWithUs: 'Work With Us',
  navRegister: 'Register',
  footerNavTitle: 'NAVIGATION',
  footerSocialTitle: 'SOCIAL MEDIA',
  footerProgramsTitle: 'LAST PROGRAMS',
  footerContactTitle: 'Contact Dilnia',
  footerBlurb:
    'Empowering innovation through strategic partnerships and sustainable growth solutions.',
  logoHomeAria: 'BIP Summit home',
  logoAlt: 'BIP Summit',
  primaryNavAria: 'Primary',
  mobileNavAria: 'Mobile',
  openChatAria: 'Open BIP AI chat',
  toggleMenuAria: 'Toggle menu',
  socialFacebook: 'Facebook',
  socialInstagram: 'Instagram',
  socialLinkedin: 'Linkedin',
  socialYoutube: 'Youtube',
  socialWhatsapp: 'Whatsapp',
  socialX: 'X',
  meetOurSpeakers: 'Meet Our Speakers',
  keySectors: 'Key Sectors',
  youtubeHighlights: 'YouTube Highlights',
  newsBlog: 'News & Blog',
  summits: 'Summits',
  gallery: 'Gallery',
  mediaChannels: 'Media & Channels',
  participatingCountries: 'Participating Countries',
  programBenefits: 'Program Benefits',
  relatedArticles: 'Related Articles',
  aboutSpeaker: 'About Speaker',
  aboutUs: 'About Us',
  contactUs: 'Contact Us',
  getInTouch: 'Get in Touch',
  ctaBandHeading: 'Get in Touch',
  pioneeringPart1: 'A pioneering program that unites ',
  pioneeringPart2: 'companies, innovators, and investors ',
  pioneeringPart3: 'for a shared future of prosperity.',
  fullName: 'Full Name',
  lastName: 'Last Name',
  companyName: 'Company Name',
  positionTitle: 'Position / Title',
  emailAddress: 'Email Address',
  phoneNumber: 'Phone Number',
  address: 'Address',
  countryRegion: 'Country Region',
  industrySector: 'Industry sector',
  partnershipType: 'Partnership Type',
  subject: 'Subject',
  message: 'Message',
  registerFormTitle: 'Register for BIP Program',
  registerSubmit: 'Register',
  joinFormTitle: 'Join BIP Program',
  joinSubmit: 'Join',
  consentEmailPrivacy:
    'I agree to receive email updates and accept the Privacy Policy.',
  consentNewsletters:
    'I agree to receive newsletters, updates, and promotional offers. I can unsubscribe at any time.',
  joinSuccessTitle: 'Successfully Registered',
  partnerFormTitle: 'Become a Partner',
  partnerSubmit: 'Submit',
  contactSubmit: 'Send Message',
  optionKurdistan: 'Kurdistan Region',
  optionIraq: 'Iraq',
  optionUae: 'United Arab Emirates',
  optionOther: 'Other',
  optionTechnology: 'Technology & AI',
  optionEnergy: 'Green Energy',
  optionHealthcare: 'Healthcare',
  optionConstruction: 'Construction',
  optionBanking: 'Banking & Finance',
  optionTourism: 'Tourism & Hospitality',
  optionFranchise: 'Franchise Development',
  optionInvestment: 'Investment',
  optionSponsor: 'Sponsor',
  optionCollaborator: 'Collaborator',
  optionMediaPartner: 'Media Partner',
  previousImage: 'Previous image',
  nextImage: 'Next image',
  worldMapAlt: 'World map showing BIP Summit participating countries',
  browseNewsAria: 'Browse news articles',
  browseSpeakersAria: 'Browse speakers',
  aboutBipAria: 'About BIP',
  pageComingSoon: 'This page is coming soon.',
  mediaHeroAlt: 'Audience at a BIP Summit event',
  chatWelcome: 'Welcome to BIP AI',
  chatSubtitle: 'Ask anything about BIP Summit',
  chatPlaceholder: 'Ask Here...',
  sendMessageAria: 'Send message',
  closeChatAria: 'Close BIP AI chat',
  chatSrOnly: 'BIP AI chat',
  chatTyping: 'BIP AI is typing…',
}

/** Sorani Kurdish (کوردی سۆرانی) — RTL */
export const LABELS_KU: LabelDict = {
  register: 'تۆمارکردن',
  learnMore: 'زیاتر بزانە',
  explore: 'گەڕان',
  viewAll: 'هەمووی ببینە',
  submit: 'ناردن',
  join: 'بەشداری بکە',
  sendMessage: 'نامە بنێرە',
  contact: 'پەیوەندی',
  joinUs: 'لەگەڵمان بەشداربە',
  askBipAi: 'پرسیار لە BIP AI بکە',
  close: 'داخستن',
  closeDialog: 'دیالۆگ دابخە',
  closeOverlay: 'داخستنی {title}',
  navHome: 'سەرەکی',
  navAbout: 'دەربارە',
  navSummits: 'کۆنفرانسەکان',
  navNews: 'هەواڵ و بلۆگ',
  navPrograms: 'بەرنامەکان',
  navContactUs: 'پەیوەندیمان پێوە بکە',
  navWorkWithUs: 'لەگەڵمان کار بکە',
  navRegister: 'تۆمارکردن',
  footerNavTitle: 'گەشتکردن',
  footerSocialTitle: 'تۆڕە کۆمەڵایەتییەکان',
  footerProgramsTitle: 'دوایین بەرنامەکان',
  footerContactTitle: 'پەیوەندی Dilnia',
  footerBlurb:
    'بەهێزکردنی داھێنان لە ڕێگەی هاوبەشی ستراتیژی و چارەسەری گەشەی بەردەوام.',
  logoHomeAria: 'سەرەکی BIP Summit',
  logoAlt: 'BIP Summit',
  primaryNavAria: 'سەرەکی',
  mobileNavAria: 'مۆبایل',
  openChatAria: 'چاتی BIP AI بکەرەوە',
  toggleMenuAria: 'مێنیو بکەرەوە/دابخە',
  socialFacebook: 'Facebook',
  socialInstagram: 'Instagram',
  socialLinkedin: 'Linkedin',
  socialYoutube: 'Youtube',
  socialWhatsapp: 'Whatsapp',
  socialX: 'X',
  meetOurSpeakers: 'قسەکەرەکانمان بناسە',
  keySectors: 'کەرتە سەرەکییەکان',
  youtubeHighlights: 'هەڵبژاردەکانی یوتیوب',
  newsBlog: 'هەواڵ و بلۆگ',
  summits: 'کۆنفرانسەکان',
  gallery: 'گەلەری',
  mediaChannels: 'میدیا و کەناڵەکان',
  participatingCountries: 'وڵاتە بەشداربووەکان',
  programBenefits: 'سوودەکانی بەرنامە',
  relatedArticles: 'وتارە پەیوەندیدارەکان',
  aboutSpeaker: 'دەربارەی قسەکەر',
  aboutUs: 'دەربارەی ئێمە',
  contactUs: 'پەیوەندیمان پێوە بکە',
  getInTouch: 'پەیوەندی بکە',
  ctaBandHeading: 'پەیوەندی بکە',
  pioneeringPart1: 'بەرنامەیەکی پێشەنگ کە کۆدەکاتەوە ',
  pioneeringPart2: 'کۆمپانیاکان، داھێنەران و وەبەرهێنەران ',
  pioneeringPart3: 'بۆ داهاتوویەکی هاوبەشی گەشەسەندوو.',
  fullName: 'ناوی تەواو',
  lastName: 'ناوی باوک / خێزان',
  companyName: 'ناوی کۆمپانیا',
  positionTitle: 'پۆست / ناونیشان',
  emailAddress: 'ئیمەیڵ',
  phoneNumber: 'ژمارەی مۆبایل',
  address: 'ناونیشان',
  countryRegion: 'وڵات / هەرێم',
  industrySector: 'کەرتی پیشەسازی',
  partnershipType: 'جۆری هاوبەشی',
  subject: 'بابەت',
  message: 'نامە',
  registerFormTitle: 'تۆمارکردن بۆ بەرنامەی BIP',
  registerSubmit: 'تۆمارکردن',
  joinFormTitle: 'بەشداری لە بەرنامەی BIP',
  joinSubmit: 'بەشداری بکە',
  consentEmailPrivacy:
    'ڕازیم بە وەرگرتنی نوێکاری ئیمەیڵ و قبوڵکردنی سیاسەتی تایبەتمەندی.',
  consentNewsletters:
    'ڕازیم بە وەرگرتنی هەواڵنامە و پێشنیارەکان. دەتوانم هەر کاتێک هەڵوەشێنمەوە.',
  joinSuccessTitle: 'بە سەرکەوتوویی تۆمارکرا',
  partnerFormTitle: 'ببە بە هاوبەش',
  partnerSubmit: 'ناردن',
  contactSubmit: 'نامە بنێرە',
  optionKurdistan: 'هەرێمی کوردستان',
  optionIraq: 'عێراق',
  optionUae: 'میرنشینە یەکگرتووەکانی عەرەبی',
  optionOther: 'هیتر',
  optionTechnology: 'تەکنەلۆژیا و زیر',
  optionEnergy: 'وزەی سەوز',
  optionHealthcare: 'تەندروستی',
  optionConstruction: 'بیناسازی',
  optionBanking: 'بانک و دارایی',
  optionTourism: 'گەشتیاری و میوانداری',
  optionFranchise: 'گەشەپێدانی فرانچایز',
  optionInvestment: 'وەبەرهێنان',
  optionSponsor: 'سپۆنسەر',
  optionCollaborator: 'هاوکار',
  optionMediaPartner: 'هاوبەشی میدیایی',
  previousImage: 'وێنەی پێشوو',
  nextImage: 'وێنەی دواتر',
  worldMapAlt: 'نەخشەی جیهان کە وڵاتە بەشداربووەکانی BIP Summit پیشان دەدات',
  browseNewsAria: 'گەڕان لە وتارە هەواڵەکان',
  browseSpeakersAria: 'گەڕان لە قسەکەرەکان',
  aboutBipAria: 'دەربارەی BIP',
  pageComingSoon: 'ئەم پەڕەیە بەم زووانە دێت.',
  mediaHeroAlt: 'ئامادەبووان لە بۆنەیەکی BIP Summit',
  chatWelcome: 'بەخێربێیت بۆ BIP AI',
  chatSubtitle: 'هەر شتێک دەربارەی BIP Summit بپرسە',
  chatPlaceholder: 'لێرە بپرسە...',
  sendMessageAria: 'نامە بنێرە',
  closeChatAria: 'چاتی BIP AI دابخە',
  chatSrOnly: 'چاتی BIP AI',
  chatTyping: 'BIP AI دەنوسێت…',
}

/** Modern Standard Arabic — RTL */
export const LABELS_AR: LabelDict = {
  register: 'سجّل',
  learnMore: 'اعرف المزيد',
  explore: 'استكشف',
  viewAll: 'عرض الكل',
  submit: 'إرسال',
  join: 'انضم',
  sendMessage: 'أرسل رسالة',
  contact: 'تواصل',
  joinUs: 'انضم إلينا',
  askBipAi: 'اسأل BIP AI',
  close: 'إغلاق',
  closeDialog: 'إغلاق الحوار',
  closeOverlay: 'إغلاق {title}',
  navHome: 'الرئيسية',
  navAbout: 'من نحن',
  navSummits: 'القمم',
  navNews: 'الأخبار والمدونات',
  navPrograms: 'البرامج',
  navContactUs: 'اتصل بنا',
  navWorkWithUs: 'اعمل معنا',
  navRegister: 'سجّل',
  footerNavTitle: 'التنقل',
  footerSocialTitle: 'وسائل التواصل',
  footerProgramsTitle: 'آخر البرامج',
  footerContactTitle: 'تواصل Dilnia',
  footerBlurb:
    'تمكين الابتكار من خلال الشراكات الاستراتيجية وحلول النمو المستدام.',
  logoHomeAria: 'الصفحة الرئيسية لـ BIP Summit',
  logoAlt: 'BIP Summit',
  primaryNavAria: 'رئيسي',
  mobileNavAria: 'جوال',
  openChatAria: 'افتح دردشة BIP AI',
  toggleMenuAria: 'تبديل القائمة',
  socialFacebook: 'Facebook',
  socialInstagram: 'Instagram',
  socialLinkedin: 'Linkedin',
  socialYoutube: 'Youtube',
  socialWhatsapp: 'Whatsapp',
  socialX: 'X',
  meetOurSpeakers: 'تعرّف على المتحدثين',
  keySectors: 'القطاعات الرئيسية',
  youtubeHighlights: 'أبرز مقاطع يوتيوب',
  newsBlog: 'الأخبار والمدونة',
  summits: 'القمم',
  gallery: 'المعرض',
  mediaChannels: 'الإعلام والقنوات',
  participatingCountries: 'الدول المشاركة',
  programBenefits: 'مزايا البرنامج',
  relatedArticles: 'مقالات ذات صلة',
  aboutSpeaker: 'عن المتحدث',
  aboutUs: 'من نحن',
  contactUs: 'اتصل بنا',
  getInTouch: 'تواصل معنا',
  ctaBandHeading: 'تواصل معنا',
  pioneeringPart1: 'برنامج رائد يجمع ',
  pioneeringPart2: 'الشركات والمبتكرين والمستثمرين ',
  pioneeringPart3: 'من أجل مستقبل مشترك من الازدهار.',
  fullName: 'الاسم الكامل',
  lastName: 'اسم العائلة',
  companyName: 'اسم الشركة',
  positionTitle: 'المنصب / المسمى',
  emailAddress: 'البريد الإلكتروني',
  phoneNumber: 'رقم الهاتف',
  address: 'العنوان',
  countryRegion: 'الدولة / المنطقة',
  industrySector: 'القطاع الصناعي',
  partnershipType: 'نوع الشراكة',
  subject: 'الموضوع',
  message: 'الرسالة',
  registerFormTitle: 'التسجيل في برنامج BIP',
  registerSubmit: 'سجّل',
  joinFormTitle: 'انضم إلى برنامج BIP',
  joinSubmit: 'انضم',
  consentEmailPrivacy:
    'أوافق على تلقي تحديثات البريد الإلكتروني وقبول سياسة الخصوصية.',
  consentNewsletters:
    'أوافق على تلقي النشرات والتحديثات والعروض. يمكنني إلغاء الاشتراك في أي وقت.',
  joinSuccessTitle: 'تم التسجيل بنجاح',
  partnerFormTitle: 'كن شريكًا',
  partnerSubmit: 'إرسال',
  contactSubmit: 'أرسل رسالة',
  optionKurdistan: 'إقليم كردستان',
  optionIraq: 'العراق',
  optionUae: 'الإمارات العربية المتحدة',
  optionOther: 'أخرى',
  optionTechnology: 'التكنولوجيا والذكاء الاصطناعي',
  optionEnergy: 'الطاقة الخضراء',
  optionHealthcare: 'الرعاية الصحية',
  optionConstruction: 'الإنشاءات',
  optionBanking: 'المصرفية والتمويل',
  optionTourism: 'السياحة والضيافة',
  optionFranchise: 'تطوير الامتياز',
  optionInvestment: 'الاستثمار',
  optionSponsor: 'راعٍ',
  optionCollaborator: 'متعاون',
  optionMediaPartner: 'شريك إعلامي',
  previousImage: 'الصورة السابقة',
  nextImage: 'الصورة التالية',
  worldMapAlt: 'خريطة العالم تُظهر الدول المشاركة في BIP Summit',
  browseNewsAria: 'تصفح مقالات الأخبار',
  browseSpeakersAria: 'تصفح المتحدثين',
  aboutBipAria: 'عن BIP',
  pageComingSoon: 'هذه الصفحة قادمة قريبًا.',
  mediaHeroAlt: 'الجمهور في فعالية BIP Summit',
  chatWelcome: 'مرحبًا بك في BIP AI',
  chatSubtitle: 'اسأل أي شيء عن BIP Summit',
  chatPlaceholder: 'اسأل هنا...',
  sendMessageAria: 'أرسل رسالة',
  closeChatAria: 'أغلق دردشة BIP AI',
  chatSrOnly: 'دردشة BIP AI',
  chatTyping: 'BIP AI يكتب…',
}

export const LABEL_LOCALES = {
  en: LABELS_EN,
  ku: LABELS_KU,
  ar: LABELS_AR,
} as const
