/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    speakers: Speaker;
    'news-articles': NewsArticle;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    'news-articles': NewsArticlesSelect<false> | NewsArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ku' | 'ar') | ('en' | 'ku' | 'ar')[];
  globals: {
    website: Website;
    pages: Page;
    sections: Section;
    translations: Translation;
  };
  globalsSelect: {
    website: WebsiteSelect<false> | WebsiteSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
  };
  locale: 'en' | 'ku' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  slug: string;
  role: string;
  image: number | Media;
  bio?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles".
 */
export interface NewsArticle {
  id: number;
  title: string;
  slug: string;
  headline: string;
  description: string;
  excerpt: string;
  image: number | Media;
  coverImage: number | Media;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  body?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'news-articles';
        value: number | NewsArticle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  image?: T;
  bio?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles_select".
 */
export interface NewsArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  headline?: T;
  description?: T;
  excerpt?: T;
  image?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, contact, navigation, and languages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website".
 */
export interface Website {
  id: number;
  siteTitle: string;
  titleTemplate: string;
  metaDescription: string;
  copyright: string;
  heroImage?: (number | null) | Media;
  pioneeringHeadline: string;
  programBlurb: string;
  programIntro: string;
  ctaBandBody: string;
  ctaBandHeading: string;
  contactEmail: string;
  phones?:
    | {
        display: string;
        /**
         * tel:+964...
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  headerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtas?: {
    contactLabel?: string | null;
    contactHref?: string | null;
    joinLabel?: string | null;
    joinHref?: string | null;
    askAiLabel?: string | null;
  };
  footerNavLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerSocialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'whatsapp' | 'x';
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerProgramLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  enableEnglish?: boolean | null;
  enableKurdish?: boolean | null;
  enableArabic?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * SEO and page-specific copy for each route
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  home: {
    seoTitle: string;
    seoDescription: string;
  };
  about: {
    seoTitle: string;
    seoDescription: string;
    eyebrow: string;
  };
  summits: {
    seoTitle: string;
    seoDescription: string;
  };
  news: {
    seoTitle: string;
    seoDescription: string;
  };
  speakers: {
    seoTitle: string;
    seoDescription: string;
    listingTitle: string;
  };
  join: {
    seoTitle: string;
    seoDescription: string;
    formTitle: string;
    successTitle: string;
  };
  partner: {
    seoTitle: string;
    seoDescription: string;
    formTitle: string;
    benefitsHeading: string;
  };
  contact: {
    seoTitle: string;
    seoDescription: string;
    eyebrow: string;
    heading: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Mission, stats, sectors, media strips, forms, AI chat
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  missionTabs?:
    | {
        /**
         * Stable id: mission | vision | what-we-do
         */
        tabId: string;
        label: string;
        lead: string;
        emphasis: string;
        trail: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sectors?:
    | {
        number: string;
        title: string;
        description: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  summitEditions?:
    | {
        year: string;
        description: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        title: string;
        /**
         * Stable id used by the frontend (e.g. tech-hub)
         */
        key: string;
        description: string;
        shortDescription: string;
        image: number | Media;
        youtubeUrl: string;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  mediaChannels?:
    | {
        label: string;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  programHighlights?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  partnership: {
    sponsor: {
      title: string;
      description: string;
      benefits?:
        | {
            number: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    collaborator: {
      title: string;
      description: string;
      benefits?:
        | {
            number: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  sectionIntros: {
    speakers: string;
    sectors: string;
    youtube: string;
    news: string;
    summits: string;
    gallery: string;
    media: string;
    countries: string;
    related: string;
  };
  formIntros: {
    register: string;
    join: string;
    partner: string;
    contact: string;
  };
  aiChat: {
    welcome: string;
    subtitle: string;
    placeholder: string;
    typing: string;
    replies?:
      | {
          text: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Button labels, nav strings, form labels (en / ku / ar)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  register: string;
  learnMore: string;
  explore: string;
  viewAll: string;
  submit: string;
  join: string;
  sendMessage: string;
  contact: string;
  joinUs: string;
  askBipAi: string;
  close: string;
  closeDialog: string;
  closeOverlay: string;
  navHome: string;
  navAbout: string;
  navSummits: string;
  navNews: string;
  navPrograms: string;
  navContactUs: string;
  navWorkWithUs: string;
  navRegister: string;
  footerNavTitle: string;
  footerSocialTitle: string;
  footerProgramsTitle: string;
  footerContactTitle: string;
  footerBlurb: string;
  logoHomeAria: string;
  logoAlt: string;
  primaryNavAria: string;
  mobileNavAria: string;
  openChatAria: string;
  toggleMenuAria: string;
  socialFacebook: string;
  socialInstagram: string;
  socialLinkedin: string;
  socialYoutube: string;
  socialWhatsapp: string;
  socialX: string;
  meetOurSpeakers: string;
  keySectors: string;
  youtubeHighlights: string;
  newsBlog: string;
  summits: string;
  gallery: string;
  mediaChannels: string;
  participatingCountries: string;
  programBenefits: string;
  relatedArticles: string;
  aboutSpeaker: string;
  aboutUs: string;
  contactUs: string;
  getInTouch: string;
  ctaBandHeading: string;
  pioneeringPart1: string;
  pioneeringPart2: string;
  pioneeringPart3: string;
  fullName: string;
  lastName: string;
  companyName: string;
  positionTitle: string;
  emailAddress: string;
  phoneNumber: string;
  address: string;
  countryRegion: string;
  industrySector: string;
  partnershipType: string;
  subject: string;
  message: string;
  registerFormTitle: string;
  registerSubmit: string;
  joinFormTitle: string;
  joinSubmit: string;
  consentEmailPrivacy: string;
  consentNewsletters: string;
  joinSuccessTitle: string;
  partnerFormTitle: string;
  partnerSubmit: string;
  contactSubmit: string;
  optionKurdistan: string;
  optionIraq: string;
  optionUae: string;
  optionOther: string;
  optionTechnology: string;
  optionEnergy: string;
  optionHealthcare: string;
  optionConstruction: string;
  optionBanking: string;
  optionTourism: string;
  optionFranchise: string;
  optionInvestment: string;
  optionSponsor: string;
  optionCollaborator: string;
  optionMediaPartner: string;
  previousImage: string;
  nextImage: string;
  worldMapAlt: string;
  browseNewsAria: string;
  browseSpeakersAria: string;
  aboutBipAria: string;
  pageComingSoon: string;
  mediaHeroAlt: string;
  chatWelcome: string;
  chatSubtitle: string;
  chatPlaceholder: string;
  sendMessageAria: string;
  closeChatAria: string;
  chatSrOnly: string;
  chatTyping: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website_select".
 */
export interface WebsiteSelect<T extends boolean = true> {
  siteTitle?: T;
  titleTemplate?: T;
  metaDescription?: T;
  copyright?: T;
  heroImage?: T;
  pioneeringHeadline?: T;
  programBlurb?: T;
  programIntro?: T;
  ctaBandBody?: T;
  ctaBandHeading?: T;
  contactEmail?: T;
  phones?:
    | T
    | {
        display?: T;
        href?: T;
        id?: T;
      };
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtas?:
    | T
    | {
        contactLabel?: T;
        contactHref?: T;
        joinLabel?: T;
        joinHref?: T;
        askAiLabel?: T;
      };
  footerNavLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerSocialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  footerProgramLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  enableEnglish?: T;
  enableKurdish?: T;
  enableArabic?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  home?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  about?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        eyebrow?: T;
      };
  summits?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  news?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
      };
  speakers?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        listingTitle?: T;
      };
  join?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        formTitle?: T;
        successTitle?: T;
      };
  partner?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        formTitle?: T;
        benefitsHeading?: T;
      };
  contact?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        eyebrow?: T;
        heading?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  missionTabs?:
    | T
    | {
        tabId?: T;
        label?: T;
        lead?: T;
        emphasis?: T;
        trail?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sectors?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  summitEditions?:
    | T
    | {
        year?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        title?: T;
        key?: T;
        description?: T;
        shortDescription?: T;
        image?: T;
        youtubeUrl?: T;
        featured?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  mediaChannels?:
    | T
    | {
        label?: T;
        logo?: T;
        id?: T;
      };
  programHighlights?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  partnership?:
    | T
    | {
        sponsor?:
          | T
          | {
              title?: T;
              description?: T;
              benefits?:
                | T
                | {
                    number?: T;
                    text?: T;
                    id?: T;
                  };
            };
        collaborator?:
          | T
          | {
              title?: T;
              description?: T;
              benefits?:
                | T
                | {
                    number?: T;
                    text?: T;
                    id?: T;
                  };
            };
      };
  sectionIntros?:
    | T
    | {
        speakers?: T;
        sectors?: T;
        youtube?: T;
        news?: T;
        summits?: T;
        gallery?: T;
        media?: T;
        countries?: T;
        related?: T;
      };
  formIntros?:
    | T
    | {
        register?: T;
        join?: T;
        partner?: T;
        contact?: T;
      };
  aiChat?:
    | T
    | {
        welcome?: T;
        subtitle?: T;
        placeholder?: T;
        typing?: T;
        replies?:
          | T
          | {
              text?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  register?: T;
  learnMore?: T;
  explore?: T;
  viewAll?: T;
  submit?: T;
  join?: T;
  sendMessage?: T;
  contact?: T;
  joinUs?: T;
  askBipAi?: T;
  close?: T;
  closeDialog?: T;
  closeOverlay?: T;
  navHome?: T;
  navAbout?: T;
  navSummits?: T;
  navNews?: T;
  navPrograms?: T;
  navContactUs?: T;
  navWorkWithUs?: T;
  navRegister?: T;
  footerNavTitle?: T;
  footerSocialTitle?: T;
  footerProgramsTitle?: T;
  footerContactTitle?: T;
  footerBlurb?: T;
  logoHomeAria?: T;
  logoAlt?: T;
  primaryNavAria?: T;
  mobileNavAria?: T;
  openChatAria?: T;
  toggleMenuAria?: T;
  socialFacebook?: T;
  socialInstagram?: T;
  socialLinkedin?: T;
  socialYoutube?: T;
  socialWhatsapp?: T;
  socialX?: T;
  meetOurSpeakers?: T;
  keySectors?: T;
  youtubeHighlights?: T;
  newsBlog?: T;
  summits?: T;
  gallery?: T;
  mediaChannels?: T;
  participatingCountries?: T;
  programBenefits?: T;
  relatedArticles?: T;
  aboutSpeaker?: T;
  aboutUs?: T;
  contactUs?: T;
  getInTouch?: T;
  ctaBandHeading?: T;
  pioneeringPart1?: T;
  pioneeringPart2?: T;
  pioneeringPart3?: T;
  fullName?: T;
  lastName?: T;
  companyName?: T;
  positionTitle?: T;
  emailAddress?: T;
  phoneNumber?: T;
  address?: T;
  countryRegion?: T;
  industrySector?: T;
  partnershipType?: T;
  subject?: T;
  message?: T;
  registerFormTitle?: T;
  registerSubmit?: T;
  joinFormTitle?: T;
  joinSubmit?: T;
  consentEmailPrivacy?: T;
  consentNewsletters?: T;
  joinSuccessTitle?: T;
  partnerFormTitle?: T;
  partnerSubmit?: T;
  contactSubmit?: T;
  optionKurdistan?: T;
  optionIraq?: T;
  optionUae?: T;
  optionOther?: T;
  optionTechnology?: T;
  optionEnergy?: T;
  optionHealthcare?: T;
  optionConstruction?: T;
  optionBanking?: T;
  optionTourism?: T;
  optionFranchise?: T;
  optionInvestment?: T;
  optionSponsor?: T;
  optionCollaborator?: T;
  optionMediaPartner?: T;
  previousImage?: T;
  nextImage?: T;
  worldMapAlt?: T;
  browseNewsAria?: T;
  browseSpeakersAria?: T;
  aboutBipAria?: T;
  pageComingSoon?: T;
  mediaHeroAlt?: T;
  chatWelcome?: T;
  chatSubtitle?: T;
  chatPlaceholder?: T;
  sendMessageAria?: T;
  closeChatAria?: T;
  chatSrOnly?: T;
  chatTyping?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}